insert into wpo_local.wpo_ctdeporte (dep_deporte, dep_slug, dep_estatus)
values
('Balonmano', 'balonmano', 1),
('Basquetbol', 'basquetbol', 1),
('Beisbol', 'beisbol', 1),
('Críquet', 'críquet', 1),
('Fut 7', 'fut-7', 1),
('Fútbol Americano', 'futbol-americano', 1),
('Fútbol de salón', 'futbol-de-salon', 1),
('Fútbol Soccer', 'futbol-soccer', 1),
('Hockey', 'hockey', 1),
('Hockey sobre césped', 'hockey-sobre-cesped', 1),
('Polo', 'polo', 1),
('Polo acuático', 'polo-acuatico', 1),
('Rugby', 'rugby', 1),
('Sóftbol', 'softbol', 1),
('Tocho bandera', 'tocho-bandera', 1),
('Ultimate Frisbee', 'ultimate-frisbee', 1),
('Voleibol', 'voleibol', 1),
('Voleibol de playa', 'voleibol-de-playa', 1)


insert into weplayone.users_ctdomainwhitelist(domain_wl_dominio)
values ('gmail.com'),
('hotmail.com'),
('outlook.com'),
('outlook.es'),
('live.com'),
('icloud.com'),
('yahoo.com'),
('aol.com'),
('zohomail.com'),
('gmx.com'),
('gmx.es'),
('protonmail.com'),
('proton.me'),
('tutanota.com'),
('tutanota.de'),
('tutamail.com'),
('tuta.io'),
('keemail.de')